[
    {
        "content": "<p>Any tips for resolving an issue where a Julia/PythonCall-based training script causes separate PyTorch DataLoader worker processes to hit an <code>ERROR: Unexpected segmentation fault encountered in worker.</code> on startup? Could the worker processes be in need of juliacall?</p>\n<p>I do not know the stack trace at this point in time, but the issue occurs in relation to the first epoch of the training process (likely when getting the first batch of data).</p>\n<p>The Julia/PythonCall-based training script creates a Python <code>torch.utils.Dataset</code>-subclass (using PythonCall - with Julia-defined implementations of the Python class methods), which is then fed to the Huggingface Accelerate-based training loop - it is a direct Python-to-Julia/PythonCall translation of <a href=\"https://github.com/Chris-hughes10/Yolov7-training/blob/main/examples/minimal_finetune_cars.py#L121-L201\">https://github.com/Chris-hughes10/Yolov7-training/blob/main/examples/minimal_finetune_cars.py#L121-L201</a> - just using a Julia-defined dataset in place of <code>CarsDatasetAdaptor</code>.</p>\n<p>The Python-training script is running just fine.</p>\n<p>It seems that the issue is not (yet) the data returned from the <code>torch.utils.Dataset</code>-subclass as it seems that the Julia-defined <code>__getitem__</code>-method is not even being invoked (nor <code>__init__</code> or <code>__len__</code>)...</p>",
        "id": 431490963,
        "sender_full_name": "Jesper Stemann Andersen",
        "timestamp": 1712311389
    }
]